--- 
apiVersion: v1
kind: Secret
metadata:
  name: database-connection-secret
# unstructured arbitrary key/value pairs, default
#type: Opaque
data:
  RDS_PORT: MzMwNg==
  RDS_DB_NAME: dG9kb3NkYg==
  RDS_USERNAME: YWRtaW4=
  RDS_PASSWORD: UGFzc3dvcmQxMjM=
  RDS_ROOT_PASSWORD: UGFzc3dvcmQxMjM=
--- 
##################################################################################################
# user service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
    - port: 4096
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v1
  template:
    metadata:
      labels:
        app: user
        version: v1
      
    spec:
      serviceAccountName: todos-api-pod
      # initContainers:
      #   - name: init-database
      #     image: busybox:1.35.0
      #     imagePullPolicy: IfNotPresent
      #     command: ["/bin/sh"]
      #     args:
      #       - "-c"
      #       - "while ! dig database; do echo Waiting for database...; sleep 2;done"
      containers:
        - name: user
          image: aparihar/todos-user-microsvc:3.0
          readinessProbe:
            httpGet:
              path: /api/user/health-check
              port: 4096
            initialDelaySeconds: 5
            periodSeconds: 10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4096
          env:
            - name: RDS_HOST
              value: "database.todos-api.svc.cluster.local"
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 300Mi
---
##################################################################################################
# group service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: group
spec:
  ports:
    - port: 5096
  selector:
    app: group
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group
      version: v1
  template:
    metadata:
      labels:
        app: group
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /api/group/metrics
        prometheus.io/port: "5096"
    spec:
      serviceAccountName: todos-api-pod
      # volumes:
      #   - name: cwagentconfig
      #     configMap:
      #       name: cwagentconfig-sidecar
      containers:
        - name: group
          image: aparihar/todos-group-microsvc:3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5096
          env:
            - name: RDS_HOST
              value: "database.todos-api.svc.cluster.local"
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
            - name: PROGRESS_TRACKER_API_HOST
              value: "progress.todos-api.svc.cluster.local"
            - name: PROGRESS_TRACKER_API_PORT
              value: "7096"
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 300Mi
        # - name: cloudwatch-agent
        #   image: amazon/cloudwatch-agent:latest
        #   imagePullPolicy: Always
        #   env:
        #     - name: POD_NAME
        #       valueFrom:
        #         fieldRef:
        #           fieldPath: metadata.name
        #   resources:
        #     limits:
        #       cpu:  100m
        #       memory: 100Mi
        #     requests:
        #       cpu: 32m
        #       memory: 24Mi
        #   volumeMounts:
        #     - name: cwagentconfig
        #       mountPath: /etc/cwagentconfig
---
##################################################################################################
# task service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: task
spec:
  ports:
    - port: 6096
  selector:
    app: task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
      version: v1
  template:
    metadata:
      labels:
        app: task
        version: v1
    spec:
      serviceAccountName: todos-api-pod
      containers:
        - name: task
          image: aparihar/todos-task-microsvc-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6096
          env:
            - name: RDS_HOST
              value: "database.todos-api.svc.cluster.local"
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
            - name: PROGRESS_TRACKER_API_HOST
              value: "progress.todos-api.svc.cluster.local"
            - name: PROGRESS_TRACKER_API_PORT
              value: "7096"
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 300Mi
---
##################################################################################################
# progress
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: progress
spec:
  ports:
    - port: 7096
  selector:
    app: progress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress
      version: v1
  template:
    metadata:
      labels:
        app: progress
        version: v1
    spec:
      serviceAccountName: todos-api-pod
      containers:
        - name: progress
          image: aparihar/todos-progress-tracker-microsvc-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7096
          env:
            - name: RDS_HOST
              value: "database.todos-api.svc.cluster.local"
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
          resources:
            limits:
              cpu: 512m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
---
##################################################################################################
# database service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: v1
  template:
    metadata:
      labels:
        app: mysql
        version: v1
      annotations:
        appmesh.k8s.aws/sidecarInjectorWebhook: disabled
    spec:
      serviceAccountName: todos-api-pod
      containers:
        - name: mysql
          image: aparihar/todos-mysql-db-microsvc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: DATABASE_HOST
              value: "database.todos-api.svc.cluster.local"
          
          resources:
            limits:
              cpu: 1024m
              memory: 2048Mi
            requests:
              cpu: 1024m
              memory: 1024Mi
        
---
