---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  backendType: systemManager
  data:
    - key: /homelabs/todos-api/jwt/accessToken
      name: JWT_ACCESS_TOKEN
---