---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: group-vr
spec:
  listeners:
    - portMapping:
        port: 5096
        protocol: http
  routes:
    - name: blue-route
      priority: 1
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: group-vn
              weight: 100
    
---