---
##################################################################################################
# virtual gateway
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: ingress-vgw
spec:
  namespaceSelector:
    matchLabels:
      gateway: ingress-gw
  podSelector:
    matchLabels:
      app: envoy-ingress-gw
  listeners:
    - portMapping:
        port: 8080
        protocol: http
      # tls:
      #   mode: STRICT
      #   certificate:
      #     file:
      #       certificateChain: /etc/tls/certs/tls.crt
      #       privateKey: /etc/tls/certs/tls.key
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-gw
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    #service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: envoy-ingress-gw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-ingress-gw
  template:
    metadata:
      labels:
        app: envoy-ingress-gw
    spec:
      serviceAccountName: todos-api-pod
      # volumes:
      #   - name: ingress-gw-cert
      #     secret:
      #       secretName: ingress-gw-cert
      containers:
        - name: envoy
          image: 840364872350.dkr.ecr.us-east-2.amazonaws.com/aws-appmesh-envoy:v1.19.0.0-prod
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 40m
              memory: 128Mi
            requests:
              cpu: 40m
              memory: 128Mi
          # volumeMounts:
          #   - name: ingress-gw-cert
          #     mountPath: /etc/tls/certs
          #     readOnly: true
--- 
