---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-root-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
spec:
  isCA: true
  commonName: ca-root-cert
  secretName: ca-root-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-root-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-private-issuer
spec:
  ca:
    secretName: ca-root-cert
---