---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-root-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
spec:
  isCA: true
  commonName: ca-root-cert
  secretName: ca-root-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-root-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-private-issuer
spec:
  ca:
    secretName: ca-root-cert
---
# Webhook Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-cert
spec:
  isCA: false
  duration: 2160h
  renewBefore: 180h
  dnsNames:
    - mutate-sa.todos-api.svc.cluster.local
  commonName: server-cert
  secretName: server-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-private-issuer
    kind: Issuer
    group: cert-manager.io
---
# K8s API server Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
spec:
  isCA: false
  duration: 2160h
  renewBefore: 180h
  dnsNames:
    - pod-sa.mytodos.com
  commonName: client-cert
  secretName: client-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-private-issuer
    kind: Issuer
    group: cert-manager.io
---