---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: todos-api-service-mesh
spec:
  egressFilter:
    type: "ALLOW_ALL"
  namespaceSelector:
    matchLabels:
      mesh: todos-api-mesh
--- 
