---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todos-api-pod
  annotations:
    eks.amazonaws.com/role-arn: 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todos-api-pod-view-role-binding
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: todos-api-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---