
---
# Webhook Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-cert
spec:
  isCA: false
  duration: 2160h
  renewBefore: 180h
  dnsNames:
    - pod-sa.todos-api.svc.cluster.local
  commonName: server-cert
  secretName: server-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-private-issuer
    kind: Issuer
    group: cert-manager.io
---
# K8s API server Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
spec:
  isCA: false
  duration: 2160h
  renewBefore: 180h
  dnsNames:
    - pod-sa-webhook.mytodos.com
  commonName: client-cert
  secretName: client-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-private-issuer
    kind: Issuer
    group: cert-manager.io
---