apiVersion: v1
kind: Namespace
metadata:
  name: calculator
  labels:
    mesh: simple-calculator-mesh
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: simple-calculator-appmesh
spec:
  egressFilter:
    type: "ALLOW_ALL"
  namespaceSelector:
    matchLabels:
      mesh: simple-calculator-mesh