---
##################################################################################################
# frontend
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      volumes:
        - name: api-gw
          configMap:
            name: frontend-api-gateway-config
            items:
              - key: default.conf
                path: default.conf
      serviceAccountName: todos-pod
      containers:
        - name: frontend
          image: aparihar/todos-mytodos-microsvc-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: USER_API_BASE_URL
              valueFrom: 
                configMapKeyRef:
                  name: frontend-env-config
                  key: USER_API_BASE_URL
            - name: GROUP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-env-config
                  key: GROUP_API_BASE_URL
            - name: TASK_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-env-config
                  key: TASK_API_BASE_URL
          volumeMounts:
            - name: api-gw
              mountPath: /etc/nginx/conf.d/
              readOnly: true
          resources:
            limits:
              cpu: 512m
              memory: 1024Mi
            requests:
              cpu: 400m
              memory: 512Mi
---
##################################################################################################
# user service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
    - port: 4096
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v1
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      serviceAccountName: todos-pod
      containers:
        - name: user
          image: aparihar/todos-user-microsvc-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4096
          env:
            - name: RDS_HOST
              value: database
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 300Mi
---
##################################################################################################
# group service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: group
spec:
  ports:
    - port: 5096
  selector:
    app: group
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group
      version: v1
  template:
    metadata:
      labels:
        app: group
        version: v1
    spec:
      serviceAccountName: todos-pod
      initContainers:
        - name: aws-cli
          image: amazon/aws-cli
          command: ["aws", "ssm", "get-parameter", "--name", "/homelabs/todos/jwt/accessToken"]
      containers:
        - name: group
          image: aparihar/todos-group-microsvc-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5096
          env:
            - name: RDS_HOST
              value: database
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
            - name: PROGRESS_TRACKER_API_HOST
              valueFrom: 
                configMapKeyRef:
                  name: backend-env-config
                  key: PROGRESS_TRACKER_API_HOST
            - name: PROGRESS_TRACKER_API_PORT
              valueFrom: 
                configMapKeyRef:
                  name: backend-env-config
                  key: PROGRESS_TRACKER_API_PORT
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 300Mi
---
##################################################################################################
# task service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: task
spec:
  ports:
    - port: 6096
  selector:
    app: task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
      version: v1
  template:
    metadata:
      labels:
        app: task
        version: v1
    spec:
      serviceAccountName: todos-pod
      containers:
        - name: task
          image: aparihar/todos-task-microsvc-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6096
          env:
            - name: RDS_HOST
              value: database
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
            - name: PROGRESS_TRACKER_API_HOST
              valueFrom: 
                configMapKeyRef:
                  name: backend-env-config
                  key: PROGRESS_TRACKER_API_HOST
            - name: PROGRESS_TRACKER_API_PORT
              valueFrom: 
                configMapKeyRef:
                  name: backend-env-config
                  key: PROGRESS_TRACKER_API_PORT
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 300Mi
              
---
##################################################################################################
# progress tracker service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: progress
spec:
  ports:
    - port: 7096
  selector:
    app: progress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress
      version: v1
  template:
    metadata:
      labels:
        app: progress
        version: v1
    spec:
      serviceAccountName: todos-pod
      containers:
        - name: progress
          image: aparihar/todos-progress-tracker-microsvc-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7096
          env:
            - name: RDS_HOST
              value: database
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PORT
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_CONN_POOL_SIZE
              value: "2"
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_TOKEN
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 300Mi
---
##################################################################################################
# database service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: v1
  template:
    metadata:
      labels:
        app: mysql
        version: v1
    spec:
      serviceAccountName: todos-pod
      containers:
        - name: mysql
          image: aparihar/todos-mysql-db-microsvc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: RDS_PASSWORD
            - name: DATABASE_HOST
              value: database
          resources:
            limits:
              cpu: 1024m
              memory: 2048Mi
            requests:
              cpu: 1024m
              memory: 1024Mi
---

