---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-api-gateway-config
data:
  default.conf: |
    server {
      # proxy requests based on routes
      location /api/user {
        proxy_pass http://user:4096;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
      location /api/group {
        proxy_pass http://group:5096;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
      location /api/task {
        proxy_pass http://task:6096;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
      location / {
          root /usr/share/nginx/html/web;
          index index.html index.htm;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env-config
data:
  USER_API_BASE_URL: "http://k8s-todos-ingressg-2c166b8b4a-61bf25cb8c894e18.elb.us-east-2.amazonaws.com/api"
  GROUP_API_BASE_URL: "http://k8s-todos-ingressg-2c166b8b4a-61bf25cb8c894e18.elb.us-east-2.amazonaws.com/api"
  TASK_API_BASE_URL: "http://k8s-todos-ingressg-2c166b8b4a-61bf25cb8c894e18.elb.us-east-2.amazonaws.com/api"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
data:
  PROGRESS_TRACKER_API_HOST: "progress"
  PROGRESS_TRACKER_API_PORT: "7096"