---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  backendType: systemManager
  data:
    - key: homelabs/todos/jwt/accessToken
      name: JWT_ACCESS_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: database-connection-secret
# unstructured arbitrary key/value pairs, default
#type: Opaque
data:
  RDS_PORT: MzMwNg==
  RDS_DB_NAME: dG9kb3NkYg==
  RDS_USERNAME: YWRtaW4=
  RDS_PASSWORD: UGFzc3dvcmQxMjM=
  RDS_ROOT_PASSWORD: UGFzc3dvcmQxMjM=
---