
---
apiVersion: v1
kind: Secret
metadata:
  name: database-connection-secret
# unstructured arbitrary key/value pairs, default
#type: Opaque
data:
  RDS_PORT: MzMwNg==
  RDS_DB_NAME: dG9kb3NkYg==
  RDS_USERNAME: YWRtaW4=
  RDS_PASSWORD: UGFzc3dvcmQxMjM=
  RDS_ROOT_PASSWORD: UGFzc3dvcmQxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
data:
  JWT_ACCESS_TOKEN: YzVjNDA4ZWQ3Zjc0NDBkY2MyNTQ3YWFmNzI5NDAxNzQyYzFkNmVmNTIwY2UyNzQxNTUyN2FiMzcwYmUwNWY2MjU5ZDQwOTExZDUzNTc4NTU1MzIwOTJjYzMzMGM1ZmEwMTdlN2YyYzcxZGEwZDY2NDk5YmM5ZTBmMzE2OGEzZTk=
