---
##################################################################################################
# database
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: database-vn
spec:
  podSelector:
    matchLabels:
      app: mysql
  listeners:
    - portMapping:
        port: 3306
        protocol: http
  serviceDiscovery:
    dns:
      hostname: mysql.todos.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: database-vs
spec:
  awsName: mysql.todos.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: database-vn
---
##################################################################################################
# user service
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: user-vn
spec:
  podSelector:
    matchLabels:
      app: user
  listeners:
    - portMapping:
        port: 4096
        protocol: http
      healthCheck:
        protocol: http
        path: "/api/user/health-check"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  serviceDiscovery:
    dns:
      hostname: user.todos.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: user-vs
spec:
  awsName: user.todos.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: user-vn
---
##################################################################################################
# group service
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: group-vn
spec:
  podSelector:
    matchLabels:
      app: group
  listeners:
    - portMapping:
        port: 5096
        protocol: http
      healthCheck:
        protocol: http
        path: "/api/group/health-check"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  serviceDiscovery:
    dns:
      hostname: group.todos.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: group-vs
spec:
  awsName: group.todos.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: group-vn
---
##################################################################################################
# task service
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: task-vn
spec:
  podSelector:
    matchLabels:
      app: task
  listeners:
    - portMapping:
        port: 6096
        protocol: http
      healthCheck:
        protocol: http
        path: "/api/task/health-check"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  serviceDiscovery:
    dns:
      hostname: task.todos.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: task-vs
spec:
  awsName: task.todos.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: task-vn
---
##################################################################################################
# frontend
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: frontend-vn
spec:
  podSelector:
    matchLabels:
      app: frontend
  listeners:
    - portMapping:
        port: 80
        protocol: http
      healthCheck:
        protocol: http
        path: "/index.html"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  backends:
    - virtualService:
        virtualServiceRef:
          name: user-vs
    - virtualService:
        virtualServiceRef:
          name: group-vs
    - virtualService:
        virtualServiceRef:
          name: task-vs
  serviceDiscovery:
    dns:
      hostname: frontend.todos.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: frontend-vs
spec:
  awsName: frontend.todos.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: frontend-vr
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: frontend-vr
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: index-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: frontend-vn
              weight: 100
---
##################################################################################################
# GatewayRoute
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: frontend-gwr
spec:
  httpRoute:
    match:
      prefix: "/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: frontend-vs
---