app_xray_tracing_enabled=false
app_appmesh_controller_enabled=true
app_kubernetes_external_secrets_enabled=true
app_app_mesh_service_discovery_enabled=false

app_aws_efs_csi_driver_enabled=false
app_prometheus_enabled=true
app_cwagent_prometheus_enabled=false