# SC and PV are cluster resources and deployed in the default ns
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kluster-sc
provisioner: efs.csi.aws.com
---
# How is the physical storage implemented
# PV is a cluster resource, manually provisioned by the cluster admin
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kluster-pv
spec:
  storageClassName: kluster-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-
---