---
##################################################################################################
# database
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: database-vn
spec:
  podSelector:
    matchLabels:
      app: mysql
  listeners:
    - portMapping:
        port: 3306
        protocol: http
  serviceDiscovery:
    dns:
      hostname: database.todos-api.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: database-vs
spec:
  awsName: database.todos-api.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: database-vn
---
##################################################################################################
# user 
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: user-vn
spec:
  podSelector:
    matchLabels:
      app: user
  listeners:
    - portMapping:
        port: 4096
        protocol: http
      healthCheck:
        protocol: http
        path: "/api/user/health-check"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  backends:
    - virtualService:
        virtualServiceRef:
          name: database-vs
  serviceDiscovery:
    dns:
      hostname: user.todos-api.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: user-vs
spec:
  awsName: user.todos-api.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: user-vr
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: user-vr
spec:
  listeners:
    - portMapping:
        port: 4096
        protocol: http
  routes:
    - name: index-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: user-vn
              weight: 100
---
##################################################################################################
# group service
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: group-vn
spec:
  podSelector:
    matchLabels:
      app: group
  listeners:
    - portMapping:
        port: 5096
        protocol: http
      healthCheck:
        protocol: http
        path: "/api/group/health-check"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  backends:
    - virtualService:
        virtualServiceRef:
          name: progress-vs
    - virtualService:
        virtualServiceRef:
          name: database-vs
  serviceDiscovery:
    dns:
      hostname: group.todos-api.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: group-vs
spec:
  awsName: group.todos-api.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: group-vr
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: group-vr
spec:
  listeners:
    - portMapping:
        port: 5096
        protocol: http
  routes:
    - name: index-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: group-vn
              weight: 100
---
##################################################################################################
# task service
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: task-vn
spec:
  podSelector:
    matchLabels:
      app: task
  listeners:
    - portMapping:
        port: 6096
        protocol: http
      healthCheck:
        protocol: http
        path: "/api/task/health-check"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  backends:
    - virtualService:
        virtualServiceRef:
          name: progress-vs
    - virtualService:
        virtualServiceRef:
          name: database-vs
  serviceDiscovery:
    dns:
      hostname: task.todos-api.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: task-vs
spec:
  awsName: task.todos-api.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: task-vr
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: task-vr
spec:
  listeners:
    - portMapping:
        port: 6096
        protocol: http
  routes:
    - name: index-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: task-vn
              weight: 100
---
##################################################################################################
# progress
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: progress-vn
spec:
  podSelector:
    matchLabels:
      app: progress
  listeners:
    - portMapping:
        port: 7096
        protocol: http
      healthCheck:
        protocol: http
        path: "/api/progress/health-check"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 10000
  backends:
    - virtualService:
        virtualServiceRef:
          name: database-vs
  serviceDiscovery:
    dns:
      hostname: progress.todos-api.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: progress-vs
spec:
  awsName: progress.todos-api.svc.cluster.local
  provider:
    
    virtualRouter:
      virtualRouterRef:
        name: progress-vr
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: progress-vr
spec:
  listeners:
    - portMapping:
        port: 7096
        protocol: http
  routes:
    - name: index-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: progress-vn
              weight: 100
---
##################################################################################################
# GatewayRoutes
##################################################################################################
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: user-gateway-route
spec:
  httpRoute:
    match:
      prefix: "/user/router"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: user-vs
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: group-gateway-route
spec:
  httpRoute:
    match:
      prefix: "/group/router"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: group-vs
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: task-gateway-route
spec:
  httpRoute:
    match:
      prefix: "/task/router"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: task-vs
---