apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must be in the form: <plural>.<group>
  name: meshedsvcs.k8s.todosapi.com
spec:
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: meshedsvcs
    singular: meshedsvc
    kind: MeshedSvc
    shortNames:
        - msvc
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.todosapi.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetPort:
                  type: integer
                svcName:
                  type: string
  